Repository NoAnyClub/elegantTypeScript, pull requests merged in 2025-04, with the labels that each got.

#32 [WEEK4] seongho
  CH04_타입_확장하기_좁히기/4.2_타입_좁히기_타입_가드/seongho.md
  CH04_타입_확장하기_좁히기/4.3_타입_좁히기_식별할_수_있는_유니온/seongho.md
  CH04_타입_확장하기_좁히기/4.4_Exhaustiveness_Checking으로_정확한_타입_분기_유지하기/seongho.md
  README.md
  assets/CH04/discriminant_union_example.png
  assets/CH04/exhaustiveness_type_check.png
  assets/CH04/fulfilled_promise_image.png
  assets/CH04/promiseSettledResult.png
  assets/CH04/promise_allSettled.png
Labels: 잘 봤습니다 👍🏻, 빠른 수정 감사합니다 ^__^, 머지 하세요!, 고생하셨습니다 🫡

#33 [WEEK4] seulgi
  CH04_타입_확장하기_좁히기/4.2_타입_좁히기_타입_가드/seulgi.md
  CH04_타입_확장하기_좁히기/4.3_타입_좁히기_식별할_수_있는_유니온/seulgi.md
  CH04_타입_확장하기_좁히기/4.4_Exhaustiveness_Checking으로_정확한_타입_분기_유지하기/seulgi.md
Labels: 잘 봤습니다 👍🏻, 머지 하세요!, 고생하셨습니다 🫡

#35 [WEEK5] seulgi
  CH05_타입_활용하기/5.1_조건부_타입/seulgi.md
  CH05_타입_활용하기/5.2_템플릿_리터럴_타입_활용하기/seulgi.md
  CH05_타입_활용하기/5.3_커스텀_유틸리티_타입_활용하기/seulgi.md
  CH05_타입_활용하기/5.4_불변_객체_타입으로_활용하기/seulgi.md
  CH05_타입_활용하기/5.5_Record_원시_타입_키_개선하기/seulgi.md
Labels: 잘 봤습니다 👍🏻, 빠른 수정 감사합니다 ^__^, 머지 하세요!, 고생하셨습니다 🫡

#34 [Week5] seongho
  CH01_들어가며/1.2_자바스크립트의_한계/seongho.md
  CH02_타입/2.2_타입스크립트의_타입_시스템/seongho.md
  CH02_타입/2.4_객체_타입/seulgi.md
  CH03_고급_타입/3.3_제네릭_사용법/seulgi.md
  CH04_타입_확장하기_좁히기/4.3_타입_좁히기_식별할_수_있는_유니온/seulgi.md
  CH05_타입_활용하기/5.1_조건부_타입/seongho.md
  CH05_타입_활용하기/5.2_템플릿_리터럴_타입_활용하기/seongho.md
  CH05_타입_활용하기/5.3_커스텀_유틸리티_타입_활용하기/seongho.md
  CH05_타입_활용하기/5.4_불변_객체_타입으로_활용하기/seongho.md
  CH05_타입_활용하기/5.5_Record_원시_타입_키_개선하기/seongho.md
  README.md
  assets/CH05/complex_to_represent.png
  assets/CH05/keyof_typeof_example.png
Labels: 잘 봤습니다 👍🏻, 빠른 수정 감사합니다 ^__^, 머지 하세요!, 고생하셨습니다 🫡

#36 [WEEK6] seulgi
  CH06_타입스크립트_컴파일/6.1_자바스크립트의_런타임과_타입스크립트의_컴파일/seulgi.md
  CH06_타입스크립트_컴파일/6.2_타입스크립트_컴파일러의_동작/seulgi.md
  CH06_타입스크립트_컴파일/6.3_타입스크립트_컴파일러의_구조/seulgi.md
  CH07_비동기_호출/7.1_API_요청/seulgi.md
  assets/CH06/kind_of_symbol.png
Labels: 잘 봤습니다 👍🏻, 머지 하세요!, 고생하셨습니다 🫡

#37 [WEEK6] seongho
  CH06_타입스크립트_컴파일/6.1_자바스크립트의_런타임과_타입스크립트의_컴파일/seongho.md
  CH06_타입스크립트_컴파일/6.2_타입스크립트_컴파일러의_동작/seongho.md
  CH06_타입스크립트_컴파일/6.3_타입스크립트_컴파일러의_구조/seongho.md
  CH07_비동기_호출/7.1_API_요청/seongho.md
  README.md
  assets/CH06/js_runtime.png
  assets/CH06/symbol.png
  assets/CH06/tokenizing.png
  assets/CH06/transfile_target.png
  assets/CH06/tsc_complie_process.png
  assets/CH06/typescript_ast.png
Labels: 빠른 수정 감사합니다 ^__^, 머지 하세요!, 고생하셨습니다 🫡
